new-admin-access:
  variations:
    default_var: false
    false_var: false
    true_var: true
  defaultRule:
    percentage:
      false_var: 20
      true_var: 80

flag-only-for-admin:
  variations:
    default_var: false
    false_var: false
    true_var: true
  targeting:
    - query: admin eq true
      percentage:
        false_var: 0
        true_var: 100
  defaultRule:
    variation: Default
