on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    defaults:
      run:
        working-directory: ./app
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Hello world action step
        uses: go-feature-flag/gofeatureflag-lint-action@eecf133b7129501054ff8b2397e13b05cc43aa8b
        id: hello          
        with:
          flagFilePath: ${{ github.workspace }}/config/flag-config.yaml
          flagFiletype: 'yaml'
